import type { ParsedFile, ValidationResult, ValidationRule } from "./types";

export function canteenDeviationMaxPoints(_rules: ValidationRule[]): number {
  return 100;
}

/**
 * The deviation report is generated by an automation, so there is little to
 * "fail" — the checklist confirms the inputs were present. The deviation itself
 * is the outcome metric tracked on the dashboard.
 */
export async function canteenDeviationValidator(
  files: ParsedFile[],
  _rules: ValidationRule[],
): Promise<ValidationResult> {
  const meta = files[0]?.statement.metadata ?? {};
  const hasSummary = Number(meta.hasSummary ?? 0) === 1;
  const hasActual = typeof meta.actualChildren === "number";
  const deviation = typeof meta.deviation === "number" ? meta.deviation : null;

  const checklist: ValidationResult["checklist"] = [
    {
      title: "Report generated",
      status: hasSummary ? "pass" : "fail",
      explanation: hasSummary ? "Summary sheet found." : "The workbook has no Summary sheet.",
      severity: "critical",
      points: hasSummary ? 50 : 0,
      maxPoints: 50,
    },
    {
      title: "Inventory report available",
      status: hasActual ? "pass" : "fail",
      explanation: hasActual
        ? `${meta.actualChildren} children recorded in the Canteen Inventory Stock Usage Report.`
        : "No inventory report children count was available for this date.",
      severity: "high",
      points: hasActual ? 50 : 0,
      maxPoints: 50,
    },
  ];
  const score = checklist.reduce((sum, c) => sum + c.points, 0);
  return {
    score,
    checklist,
    summary:
      deviation === null
        ? "Deviation could not be computed."
        : `Children deviation (Inventory − Expected): ${deviation > 0 ? "+" : ""}${deviation}.`,
    recommendations: hasActual ? [] : ["Submit the Canteen Inventory Stock Usage Report for this date."],
  };
}
