"use node";

import type { ParsedStatement } from "../../validators/types";

/**
 * Parses a Master Fees payment receipt PDF used as proof of deposit for the
 * Canteen Sales Collection.
 *
 * The PDF is generated by the Master Fees system and contains:
 *   RECEIPT No <id>
 *   Date <MM/DD/YYYY>
 *   Method  <MOBILE MONEY | CASH | …>
 *   Amount Paid - <Method> (P)  -ZMW <amount>
 *
 * Metadata keys produced (consumed by canteenSalesRecon validator):
 *   date         – ISO date of the receipt (yyyy-mm-dd)
 *   amountPaid   – absolute ZMW amount paid (positive number)
 *   receiptNo    – receipt identifier string
 *   paymentMethod
 */
export async function parseCanteenReceiptPdf(buffer: ArrayBuffer): Promise<ParsedStatement> {
  // Polyfills required by pdf-parse's canvas dependency in a Node environment.
  if (typeof global !== "undefined") {
    if (!("DOMMatrix"  in global)) (global as any).DOMMatrix  = class DOMMatrix  {};
    if (!("ImageData"  in global)) (global as any).ImageData  = class ImageData  {};
    if (!("Path2D"     in global)) (global as any).Path2D     = class Path2D     {};
  }

  const { PDFParse } = await import("pdf-parse");
  const parser = new PDFParse({ data: new Uint8Array(buffer) });
  const { text } = await parser.getText();
  await parser.destroy();

  // ── Date ─────────────────────────────────────────────────────────────────────
  // "Date 6/30/2026" or "Date: 2026-01-15"
  let date: string | null = null;
  const dateMatch =
    text.match(/Date[:\s]+(\d{1,2}\/\d{1,2}\/\d{4})/) ??
    text.match(/Date[:\s]+(\d{4}-\d{2}-\d{2})/);
  if (dateMatch) {
    const raw = dateMatch[1];
    // Master Fees emits MM/DD/YYYY (US locale from the system).
    const slashM = raw.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);
    if (slashM) {
      date = `${slashM[3]}-${slashM[1].padStart(2, "0")}-${slashM[2].padStart(2, "0")}`;
    } else {
      date = raw; // already ISO
    }
  }

  // ── Amount paid ───────────────────────────────────────────────────────────────
  // "Amount Paid - MOBILE MONEY (P) -ZMW 400.00"
  // We strip commas so "1,200.00" → 1200.
  let amountPaid: number | null = null;
  const amtMatch = text.match(/Amount Paid[^Z\d]*ZMW\s*([\d,]+\.?\d*)/i);
  if (amtMatch) {
    amountPaid = parseFloat(amtMatch[1].replace(/,/g, ""));
    if (!Number.isFinite(amountPaid)) amountPaid = null;
  }

  // ── Receipt number ────────────────────────────────────────────────────────────
  let receiptNo: string | null = null;
  const receiptMatch = text.match(/RECEIPT\s+No\.?\s*([A-Z0-9]+)/i);
  if (receiptMatch) receiptNo = receiptMatch[1].trim();

  // ── Payment method ────────────────────────────────────────────────────────────
  let paymentMethod: string | null = null;
  const methodMatch = text.match(/Method\s+([A-Z][A-Z\s]+?)(?:\n|Logged)/i);
  if (methodMatch) paymentMethod = methodMatch[1].trim();

  return {
    openingBalance: null,
    closingBalance: null,
    transactions: [],
    metadata: { date, amountPaid, receiptNo, paymentMethod },
  };
}
